---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: usuarios y publicaciones
  checked: false
- value: usuarios y likes
  checked: false
- value: usuarios y usuarios
  checked: true
- value: usuarios y comentarios
  checked: false
